### ISSUE TITLE
Multiple Countries with same Prefix

### ISSUE THREAD

**Issue by StevenReid** [mozziemozz/TeamsPhoneAutomation#1]
Hi,
When the CountryLookupTable.json file has multiple entries for the same prefix, the last one gets used in the list.

The phone numbers I am adding are all +61 for Australia, but the Country that gets added to the list is CC

Here are the 3 entries that are in the json file.

    {
        "Prefix": "+61",
        "CountryName": "Australia",
        "Country": "AU"
    },
    {
        "Prefix": "+61",
        "CountryName": "Christmas Island",
        "Country": "CX"
    },
    {
        "Prefix": "+61",
        "CountryName": "Cocos Islands",
        "Country": "CC"
    },

Should we just remove the values that we don't use?

**Comment by mozziemozz** [comment]
Hi Steven, yes, that‘s one approach. Or if all your +61 numbers are followed by e.g. 123 you can just add it to the Prefix in the json. It checks for starts with so you can basically enter all digits which are always the same as the prefix.

Please note that I have been making some improvements and changes in the repo but I havent had time to update the blog yet. Things might look slightly different than show in the blog..

**Comment by StevenReid** [comment]
Thank you

I saw the code after I raised the issue, and I saw the logic.


Thanks


Steven Reid MCP
IT Manager

[cid:FitzFinancialGroup_3212012f-9a66-4d55-864f-0cc844ef684a.png]

P 07 3105 6500 D 07 3105 6545 M 0419 798 949 F 07 3831 7377 E ***@***.******@***.***>
GPO Box 273, Brisbane QLD 4001
Level 23, 215 Adelaide St, Brisbane QLD 4000

www.fitz.com.au<http://www.fitz.com.au>

Fitzpatricks Private Wealth, ABN 33 093 667 595, holder of Australian Financial Services Licence (AFSL) No. 247 429, and Atrium Investment Management Pty Ltd (Atrium), ABN 17 137 088 745, holder of AFSL 338 634. The content of this email contains general information only and is not intended to provide you with advice or take into account your objectives, financial situation or needs. When we provide you with advice this will be set out and recorded in an eligible advice document. The views expressed in this email and our website are the opinions of the authors at the time of writing and do not constitute a recommendation to act. All information referenced are believed to be accurate at the time of compilation and is provided by Fitzpatricks Private Wealth or Atrium in good faith. The information contained in this email is confidential. It is intended solely for the addressee. If you receive this email in error please contact the sender and delete the email. With the exception of any personal advice provided, Fitzpatricks Private Wealth and Atrium have no liability (including liability in negligence) to any person for any loss or damage consequential or otherwise suffered or incurred by that person resulting directly or indirectly from either the use of, or reliance on, the information contained herein. Fitzpatricks Private Wealth and Atrium do not guarantee the performance of any fund, stock or the return of an investor's capital. Past performance is not a reliable indicator of future performance.

FTZ-001 20210902

________________________________

**Comment by mozziemozz** [comment]
https://medium.com/@mozzeph/teams-phone-number-management-list-part-2-b5385e348a3a

If you have more prefixes from the same country in your number ranges, just add more entries with different prefixes but with the same country.

```
{
    "Prefix": "+1206",
    "CountryName": "United States",
    "Country": "US"
},
{
    "Prefix": "+1323",
    "CountryName": "United States",
    "Country": "US"
}
```
