### ISSUE TITLE
MicrosoftTeams Powershell Module always reinstalled

### ISSUE THREAD

**Issue by mdurini-swisscom** [mozziemozz/TeamsPhoneAutomation#2]
The module is reinstalled every time. The last two lines are not returning values 

$localTeamsPSVersion = Get-InstalledModule -Name "MicrosoftTeams"
$localTeamsPSVersionMajor = $localTeamsPSVersion.Version.Major
$localTeamsPSVersionMinor =$localTeamsPSVersion.Version.Minor

**Comment by mozziemozz** [comment]
should be fixed now
