### ISSUE TITLE
Benutzerinformationsliste list not found

### ISSUE THREAD

**Issue by mdurini-swisscom** [mozziemozz/TeamsPhoneAutomation#3]
This command is not returning any result

$userInformationListId = (Invoke-RestMethod -Method Get -Headers $Header -Uri "https://graph.microsoft.com/v1.0/sites/$($sharePointSite.id)/lists?`$filter=displayName eq 'Benutzerinformationsliste'").value.id

as I understood, Benutzerinformationsliste is the User Information List, a hidden list containing all the users stored in a SharePoint site. Benutzerinformationsliste  seems to be the German name.

**Comment by mdurini-swisscom** [comment]
I can get the name via the url, but if i try to substitute it, I still get an empty result. If i'm running the command without the filter option in the URL, i get two lists
- Teams Phone Number Overview (this is the second time that i'm running this script, so the list was already created)
- Documenti condivisi (Shared documents in English)
I'm trying to debug this script because the function "Get-AllSPOListItems" is triggering an error due to empty value of the parameter ListId, that is supposed to be the variable $userInformationListId (row 104 script TeamsPhoneNumberOverview.ps1)

**Comment by mozziemozz** [comment]
So what is the name of the user information list in your language?

`$userInformationListId = (Invoke-RestMethod -Method Get -Headers $Header -Uri "https://graph.microsoft.com/v1.0/sites/$($sharePointSite.id)/lists?`$filter=displayName eq 'Benutzerinformationsliste'").value.id
`
You should be able to replace Benutzerinformationsliste with the list name in your language. Keep the white spaces and the '' surrounding the name. Also keep the back tick before the `$.

This worked for me in German and English.

`$userInformationListId = (Invoke-RestMethod -Method Get -Headers $Header -Uri "https://graph.microsoft.com/v1.0/sites/$($sharePointSite.id)/lists?`$filter=displayName eq 'User Information List'").value.id
`

**Comment by mdurini-swisscom** [comment]
The funny thing is that I don't get it from powershell but i can find it from the URL
![image](https://user-images.githubusercontent.com/93028373/231355041-765ed5dd-49fe-43c9-b474-241d73bef6f0.png)

even removing the filter part from the url is not showing it

![image](https://user-images.githubusercontent.com/93028373/231355225-bff8b891-bcad-4e46-8ff6-f3ac6900420b.png)

**Comment by mozziemozz** [comment]
The filter part has to be there. Otherwise it won't be found because it's hidden. If it was found without the filter, it would have made things a lot easier. I checked my tenant again yesterday. In the browser it's called User Information List but with PS I can only find it using Benutzerinformationsliste. I suggest to search what possible names in the language of your tenant are.

**Comment by mdurini-swisscom** [comment]
It makes sense now. you can close this issue ;) thank you

**Comment by mozziemozz** [comment]
I think I found a way to dynamically get the id of the user information list, regardless of the localization.
https://github.com/mozziemozz/TeamsPhoneAutomation/commit/6cbb1a4b9160c0b2dcd62753868249916acbd9ab
