### ISSUE TITLE
Error received during setup and when running the script

### ISSUE THREAD

**Issue by waynesims** [mozziemozz/TeamsPhoneAutomation#5]
At setup I get the following error, even though it continues to allow me to select the correct subscription and deployment completes.
Sleeping for 30s to give Azure some time to apply the permissions...
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Temp\Github\Setup\Setup.ps1:283 char:26
+ ... yRoleId = ((Invoke-RestMethod -Method Get -Headers $Header -Uri "http ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

When the script runs I get 3 Access Denied errors:

Get-CsPhoneNumberAssignment : Access Denied. At C:\Temp\hmc2gh5h.jv5\Get-CsOnlineNumbers.ps1:17 char:9 + $csOnlineNumbers = Get-CsPhoneNumberAssignment -NumberType $n ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: ({ TelephoneNumb... 500, Skip = }:<>f__AnonymousType56`15) [Get-CsPhoneNumberAssignment_Get], RestException`1 + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsPhoneNumberAssignment_Get

Get-CsPhoneNumberAssignment : Access Denied. At C:\Temp\hmc2gh5h.jv5\Get-CsOnlineNumbers.ps1:17 char:9 + $csOnlineNumbers = Get-CsPhoneNumberAssignment -NumberType $n ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: ({ TelephoneNumb... 500, Skip = }:<>f__AnonymousType56`15) [Get-CsPhoneNumberAssignment_Get], RestException`1 + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsPhoneNumberAssignment_Get

Get-CsOnlineUser : Access Denied. At line:391 char:1 + $allTeamsPhoneUsers = Get-CsOnlineUser -Filter "LineURI -ne `$null" + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: ({ PageSize = , ...eleteduser = }:<>f__AnonymousType93`13) [Get-CsOnlineUser], RestException`1 + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineUser

**Comment by mozziemozz** [comment]
I think there's something wrong with how you downloaded/cloned the repository. Your setup script is located at  C:\Temp\Github\Setup\Setup.ps1 but the functions are at C:\Temp\hmc2gh5h.jv5\Get-CsOnlineNumbers.ps1.

Please try to clone the repo again and make sure it's in it's own subfolder under C:\Temp\GitHub e.g. C:\Temp\GitHub\TeamsPhoneAutomation.
