### ISSUE TITLE
Adding new entries in sharepoint when run local mode

### ISSUE THREAD

**Issue by lazy-buccaneer** [mozziemozz/TeamsPhoneAutomation#6]
I'm running the code locally, after first run the entries are adding as new every time even though the phone numbers are present in the sharepoint.

**Comment by mozziemozz** [comment]
Did you also create the flow in PowerAutomate or not? I just tested locally on my machine and it's working fine. Can you provide more info like screenshots or console output? Thanks

**Comment by lazy-buccaneer** [comment]
It is working after creating the flow in PowerAutomate.
